// ===== 翻译语言列表 =====
export var LANG_LIST = [
    {"code": "auto", "name": "自动检测"},
    {"code": "zh", "name": "中文"},
    {"code": "en", "name": "英语"},
    {"code": "ja", "name": "日语"},
    {"code": "jp", "name": "日语"},
    {"code": "ko", "name": "韩语"},
    {"code": "kor","name": "韩语"},
    {"code": "fr", "name": "法语"},
    {"code": "fra","name": "法语"},
    {"code": "de", "name": "德语"},
    {"code": "es", "name": "西班牙语"},
    {"code": "spa","name": "西班牙语"},
    {"code": "pt", "name": "葡萄牙语"},
    {"code": "ru", "name": "俄语"},
    {"code": "ar", "name": "阿拉伯语"},
    {"code": "ara","name": "阿拉伯语"},
    {"code": "vi", "name": "越南语"},
    {"code": "th", "name": "泰语"},
    {"code": "it", "name": "意大利语"},
    {"code": "nl", "name": "荷兰语"},
    {"code": "pl", "name": "波兰语"},
    {"code": "tr", "name": "土耳其语"},
    {"code": "id", "name": "印尼语"},
    {"code": "ms", "name": "马来语"},
    {"code": "hi", "name": "印地语"},
    {"code": "sv", "name": "瑞典语"},
    {"code": "da", "name": "丹麦语"},
    {"code": "fi", "name": "芬兰语"},
    {"code": "no", "name": "挪威语"},
    {"code": "cs", "name": "捷克语"},
    {"code": "ro", "name": "罗马尼亚语"},
    {"code": "hu", "name": "匈牙利语"},
    {"code": "el", "name": "希腊语"},
    {"code": "he", "name": "希伯来语"},
    {"code": "uk", "name": "乌克兰语"},
    {"code": "fa", "name": "波斯语"},
];
